import re


class SQLValidator:
    """
    Validate SQL queries generated by the LLM.

    Only read-only SELECT queries are allowed.
    """

    FORBIDDEN_KEYWORDS = [

        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "CREATE",
        "PRAGMA",
        "ATTACH",
        "DETACH",
        "VACUUM",
        "REINDEX",
        "TRUNCATE",
        "REPLACE",

    ]

    def validate(
        self,
        sql: str
    ) -> tuple[bool, str]:
        """
        Returns
        -------
        (True, "") if valid.

        (False, reason) otherwise.
        """

        sql = sql.strip()

        # ---------------------------------------
        # Must start with SELECT
        # ---------------------------------------

        if not sql.upper().startswith("SELECT"):

            return False, "Only SELECT queries are allowed."

        # ---------------------------------------
        # Reject multiple statements
        # ---------------------------------------

        statements = [

            statement

            for statement in sql.split(";")

            if statement.strip()

        ]

        if len(statements) > 1:

            return False, "Multiple SQL statements are forbidden."

        # ---------------------------------------
        # Reject dangerous keywords
        # ---------------------------------------

        sql_upper = sql.upper()

        for keyword in self.FORBIDDEN_KEYWORDS:

            if re.search(rf"\b{keyword}\b", sql_upper):

                return False, f"Forbidden keyword detected: {keyword}"

        # ---------------------------------------
        # Reject sqlite internal tables
        # ---------------------------------------

        if "SQLITE_MASTER" in sql_upper:

            return False, "Access to sqlite_master is forbidden."

        if "SQLITE_SEQUENCE" in sql_upper:

            return False, "Access to sqlite_sequence is forbidden."

        return True, ""